### ISSUE TITLE
Feature Request: Change Button Icons

### ISSUE THREAD

**Issue by Nariaftw** [Kaldaien/UnX#1]
It seems the client likes to show Xbox controller button icons by default, with no obvious way to configure this. I personally use a PS3 controller, wirelessly, through the SCP drivers (which are EXCELLENT!), and am hoping there's an easy fix to show the proper button icons. I haven't confirmed yet, but given that this port is based on the PS3/4 version, it's likely the proper icons are still in the file tree somewhere. Would it be within scope of this project to have a setting for this?

I guess I'm hoping it could be accomplished in a similar fashion to the language options you have implemented.

Either way, thank you for you time and effort already, it is greatly appreciated!

**Comment by IceLancerSR** [comment]
second this!
i am a playstation :+1:  child. xbox has no meaning to me :-1:

**Comment by Kaldaien** [comment]
I am going to work on this, it will require writing some new d3d11 code which is still pretty foreign to me. I work primarily with GL and can get by with d3d9 thanks to tools like GeDoSaTo ;)

I don't have any time estimates, but the way it'll work is you just dump the current buttons and use them as template and then I can inject a replacement .dds texture. Same as all my other mods.

**Comment by Nariaftw** [comment]
Out of curiousity, do you have a way to reliably browse through the file structure in the archives? I have a sinking suspicion that the proper icons might already be hidden in there somewhere given that they displayed on the previous versions on PS3/4, and it seems like a pretty square thing to do to leave the files kicking around.

I haven't peered at how any of the code works, but I imagine if it were in there, you could do some sneaky references like you pulled off for the language files?

Just a thought! Thank you for looking into it either way, engine/graphics programming is way beyond me.

**Comment by IceLancerSR** [comment]
for the moment as far as i know .vbf cant be repacked yet.
but yes buttons are most definitely there since source is ps3 ps4 ,they always are.

**Comment by Nariaftw** [comment]
Wouldn't really need to be repacked in this case. The idea being if the files are there, use a similar trick to the audio to effectively symlink to the icons we would like it to render instead.

**Comment by IceLancerSR** [comment]
you know, at this moment i am totally fine how ever he make it work.. :-) 
because i am totally delaying playing the game since i miserably failed at start attempting overdrive with xbox buttons...

**Comment by Kaldaien** [comment]
Texture dumping is complete and I have dumped the gamepad texture and included it on the 0.0.4 download page. The system to load new textures is not complete though, so I've just released this texture ahead of time so people can get started working on it while I do the technical stuff behind the scenes.

>The is no need to ever repack files with my mods; in fact I abhor that entire process. I do not like major changes that cannot be undone simply :)

>I prefer to dump and inject textures as the graphics engine loads them.

**Comment by Kaldaien** [comment]
PS3 buttons are live in v 0.0.4

**Comment by IceLancerSR** [comment]
Textures look good. 
unx config should probably be in jpn and not en, but that doesnt matter now.
how to load them into game is a question for zillion  :+1:  :)

**Comment by IceLancerSR** [comment]
Success !!
http://imgur.com/IWMpp64

**Comment by yukimono** [comment]
Just some fun trivia: /FFX_Data/GameData/PS3Data/menu/D3D11/icon.dds.phyre still has the PS4 icons (as does the same file in the PS3 release)

**Comment by Kaldaien** [comment]
Thank you for that, I will look into adding an option to use the official buttons when possible. For now, I'm happy with the current solution for 3rd party buttons :)
