### ISSUE TITLE
MaxDeltaTime

### ISSUE THREAD

**Issue by IceLancerSR** [Kaldaien/UnX#13]
I am half way through the game and i have not experienced slow loading yet.
BUT i use MaxDeltaTime=0 the moment i updated inis from ur git with MaxDeltaTime=3 i get massive frames skips during recording.

Also on side note, left trigg+right trigg+start +sel (or just start) has no effect in my game what so ever.
Using Logitech Rumblepad 2 it doesnt have xinput.

Nvidia gtx 950 and bandicam.latest

**Comment by Kaldaien** [comment]
I see, I just sort of assumed the game didn't even support DirectInput like 99% of JRPGs ;)

I can fix this in a later version.

**Comment by IceLancerSR** [comment]
its working flawlessly,not like pesky xbox gamepads which disobey to work on ffx :P

**Comment by Kaldaien** [comment]
Is your controller the one with the numbered buttons?

I may need your help testing something. I've gotten a rudimentary DirectInput wrapper up and running, but I only did a mapping for PS3/PS4 controllers --> XInput button layout. I don't know what numbers your controller fires off (in Joy.cpl) for these functions.

What I have for PS4 controllers is this:

    Square = 1
    Cross = 2
    Circle = 3
    Triangle = 4
    L1 = 5
    R1 = 6
    L2 = 7
    R2 = 8
    Select = 9
    Start = 10
    L3 = 11
    R3 = 12

I'd like to confirm the general layout is the same on generic gamepads as well.

**Comment by IceLancerSR** [comment]
Sorry it took so long, just got home
http://imgur.com/prUZs67
this is button mapping

**Comment by IceLancerSR** [comment]
Everything is working as intended.
Although i still cannot record properly with "default" maxdeltatime=3
game starts hanging for second-two constantly.
maxdelta=0 is still working without issues for me tho
intel 2500k and nvidia gtx950

**Comment by Kaldaien** [comment]
Things should be working as intended now, I've opted to turn the MaxDeltaTime fix off after doing testing on my laptop's AMD and Intel GPUs.
