### ISSUE TITLE
Voiceover always Japanese

### ISSUE THREAD

**Issue by kieraneglin** [Kaldaien/UnX#14]
Running 0.11, no matter what I change the INI to, the voiceover is always Japanese.  Subtitles are english.

**Comment by Kaldaien** [comment]
This is probably to blame:

    struct {
      std::wstring voice = L"jp";
      std::wstring video = L"jp";
      std::wstring sfx   = L"jp";
    } language;

If the INI file cannot be parsed, it defaults to "jp". That said, any value other than "jp" will work. So it's likely that the INI file is never even being read. Either that or you used one of the modified executables on Steam. I cannot fix those.
