### ISSUE TITLE
Updated icons

### ISSUE THREAD

**Issue by Continuity28** [Kaldaien/UnX#15]
I don't know if this is the right place to put this, but I have updated all my icons and added support for FFX-2.

I have sets for:
PS3
PS4
Xbox 360
Xbox One

I know you can't package every texture from every person in the mod, but since you already have my older icons in the mod by default, I figured they could be replaced.

https://drive.google.com/open?id=0Bxb5Tb8W1j0nOXV3OTZObFJCX2c

**Comment by IceLancerSR** [comment]
D-pads are better then old single pointing arrows :)
square should be bit more pronounced ,bigger.select and start are good.
if you could add some gloss to buttons and maybe curve them a bit , so they dont look so flat :)

**Comment by Kaldaien** [comment]
Got it, thanks.

The updated textures will be included in 0.2.0 later today.
