### ISSUE TITLE
Feature request: Soft reset

### ISSUE THREAD

**Issue by Zireael** [Kaldaien/UnX#17]
Hi, on the console version it was possible to return to game title/load save screen by pressing  L1+L2+R1+R2+Start+Select (for fast savegame reloading)
UnX is doing all kinds of hacks with Start/Select + button now, so one has to be careful what they press on the gamepad/keyboard.

Would it be possible to:
1) add soft reset by pressing gamepad combination
2) add config toggle that enables/disables the hack button combos for gamepad/keyboard

Thanks!

**Comment by Kaldaien** [comment]
There's already settings to disable the buttons. Just edit UnX_Gamepad.ini and set F1 - F5 to blank lines.

A soft reset would be something i'd love to do, but unless the code still exists in the PC version but is disabled it isn't generally practical. It's not entirely impossible, I've worked on enough of these games to know that there's code from multiple platforms lying dormant often :)

Finding it would be the tricky part, I haven't spent any time analyzing the game at the assembly level yet.

**Comment by IceLancerSR** [comment]
I will quote one person who said it better then i would with my English..
"the restart you did with the Select+start+4shoulders was not part of this game
it's actually the Soft reset function on the playstation itself
if you Had a playstation 1 you can do it with every game"
So better question would be can u reinvent soft reset of PC :P

**Comment by Nariaftw** [comment]
That's actually not true, it wasn't a baked in firmware feature of the PS1 or 2, at least not being triggered by the button combo. A lot of games had a form of soft reset though, but it was never a universal thing on either console.

One thing I could recommend, and it's honestly about as fast. The latest versions of UnX support opening the ESC menu with a button combo, that when paired with Xan's new launcher ( http://steamcommunity.com/app/359870/discussions/0/364042063113591969/ ) would allow you to get out of the game and back in super fast.

I know on my system I can close the game, and be back to skipping the intro movies in mere seconds.

**Comment by IceLancerSR** [comment]
Hm.. might be that you are right.After your post i did some googling.It seems that games do have embedded in them soft reset function.Finding the code is another matter. 
I found out that  some games lost the ability , example is FFVII for PS4 got code replaced with "quit" so yeah i guess this might still have code in it.

**Comment by Kaldaien** [comment]
This has been added to 0.5.3 (FFX). FFX-2 will follow in a future release.
