### ISSUE TITLE
Feature request: mute sounds on Alt-Tab

### ISSUE THREAD

**Issue by Zireael** [Kaldaien/UnX#18]
Hi,
Firstly thanks for making this project, it makes the game much more friendly!
A feature I'd hope to have is, when the game window loses focus, the game sounds would stop being audible.
It's for multitasking, such as answering a Skype call or popping in MMO game to chat with friends, etc.
I know you can mute programs in systray, but would be cool if it was happening seamless.

NB, Kaldaien, you are aware of the GUI for UnX settings in this lancher? 
https://github.com/xan105/FFX-X2_LAUNCHER/releases/
Compliments UnX quite well.

**Comment by Kaldaien** [comment]
Sorry I didn't respond quicker, I finally got around to implementing this in 0.3.0.
