### ISSUE TITLE
API-MS-WIN-SHCORE-SCALING-L1-1-1.DLL missing err?

### ISSUE THREAD

**Issue by IceLancerSR** [Kaldaien/UnX#2]
As soon as i start FFX this pops up.. i tried googling but cant find answer, it seems some library only for Win8 and higher? i am on win7 sp1x64

API-MS-WIN-SHCORE-SCALING-L1-1-1.DLL

and my net seems to be in order

<32Bit>
2.0.50727.5485
  ->C:\Windows\Microsoft.NET\Framework\v2.0.50727
4.6.1055.0
  ->C:\Windows\Microsoft.NET\Framework\v4.0.30319

<64Bit>
2.0.50727.5485
  ->C:\Windows\Microsoft.NET\Framework64\v2.0.50727
4.6.1055.0
  ->C:\Windows\Microsoft.NET\Framework64\v4.0.30319

< Installed .NET Frameworks >
.NET FW 2.0 SP 2  (CLR:2.0)
.NET FW 3.0 SP 2  (CLR:2.0)
.NET FW 3.5 SP 1  (CLR:2.0)
.NET FW 4.6.2  (CLR:4.0)

< Installed Updates >
Microsoft .NET Framework 4 Client Profile 
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
Microsoft .NET Framework 4 Extended 
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
Microsoft .NET Framework 4 Multi-Targeting Pack 
 KB2504637 Update for  (KB2504637)
Microsoft .NET Framework 4.5 
 KB2729460
 KB2737083
 KB2742613
 KB2745582
 KB2748645
 KB2750147
 KB2756203
 KB2759112
 KB2783808
 KB2789648
 KB2794055
 KB2803754
 KB2804582
 KB2805221
 KB2805226
 KB2805290
 KB2822218
 KB2823493
 KB2828841
 KB2835622
 KB2858725
 KB2861193
 KB2861208
 KB2862063
 KB2872778
 KB2885201
 KB2889889
 KB2894849
 KB2894854
 KB2898864
 KB2898869
 KB2901118
 KB2901126
 KB2901983
 KB2908383
 KB2925382
 KB2931368
 KB2936388
 KB2937676
 KB2938782
 KB2954853
 KB2969355
 KB3006566
 KB3033093
 KB3045561
 KB3076093
 KB3086153
 KB3088517
 KB3102433

< Installed Languages 3.0>
English - United States
< Installed Languages 3.5.x>
English - United States
< Installed Languages 4.x>
English - United States

what is that error then?

**Comment by IceLancerSR** [comment]
P.S
here is log from ur dxgi
05/13/2016 15:34:37.076: dxgi.log created
-----------------------------------------------------------------------------------
05/13/2016 15:34:37.139: >> (FFX.exe) [dxgi.dll] <<

05/13/2016 15:34:37.139: Loading user preferences from dxgi.ini... done!
-----------------------------------------------------------------------------------
05/13/2016 15:34:37.157:  System Directory:           C:\Windows\SysWOW64
05/13/2016 15:34:37.157:  Loading default dxgi.dll:  (C:\Windows\SysWOW64\dxgi.dll)
-----------------------------------------------------------------------------------
05/13/2016 15:34:37.180:   * Loading Early Custom Import unx.dll... failed: 0x0000 (The specified module could not be found.)!
05/13/2016 15:34:39.547: Initializing NvAPI:  Success

05/13/2016 15:34:39.562:  >> NVIDIA Driver Version: 364.72
05/13/2016 15:34:39.562:   * Number of Installed NVIDIA GPUs: 1 (0 are in SLI mode)

05/13/2016 15:34:39.562:   NvOptimusEnablement..................: UNDEFINED
05/13/2016 15:34:39.562:   AmdPowerXpressRequestHighPerformance.: UNDEFINED

05/13/2016 15:34:39.562: Importing CreateDXGIFactory{1|2}
05/13/2016 15:34:39.562: ================================
05/13/2016 15:34:39.562:   CreateDXGIFactory:  69097542h
05/13/2016 15:34:39.562:   CreateDXGIFactory1: 690975FBh
05/13/2016 15:34:39.562:   CreateDXGIFactory2: 00000000h
05/13/2016 15:34:39.562: === Initialization Finished! ===

05/13/2016 15:34:39.856: [!] CreateDXGIFactory1 (IDXGIFactory, 002FED2Ch) -- [Calling Thread: 0x10f8]
05/13/2016 15:34:39.856:   Calling original function: (ret=S_OK)

05/13/2016 15:34:39.984: [!] CreateDXGIFactory1 (IDXGIFactory, 002FED58h) -- [Calling Thread: 0x10f8]
05/13/2016 15:34:39.984:   Calling original function: (ret=S_OK)

05/13/2016 15:34:40.057: [!] IDXGIFactory2::CreateSwapChain (04B8F284h, 00B94F78h, 00B94F74h) -- [Calling Thread: 0x10f8]
05/13/2016 15:34:40.057:   SwapChain: (2048x1152 @ 60.0 Hz - Scaling: Unspecified) - {Windowed} [1 Buffers] :: Flags=0x0002, SwapEffect: Discard
05/13/2016 15:34:40.074:  >> Using Traditional Presentation Model  [Waitable: No]
05/13/2016 15:34:40.074:   Calling original function: (ret=S_OK)

05/13/2016 15:34:41.766:   # Found window in 2.2 seconds, installing keyboard hook...
05/13/2016 15:34:41.766:   * Installed keyboard hook for command console... 1 try (0 ms!)
05/13/2016 15:34:47.250: Unloading Custom Import unx.dll... failed: 0x0000 (%1 is not a valid Win32 application.)!
05/13/2016 15:34:47.250: [RTSS] Closing RivaTuner Statistics Server connection...

**Comment by IceLancerSR** [comment]
Ok i got dll separate into game folder to be beside ur dll and now it fails at "SetProcessDpiAwarness could not be located in the dynamic link library"

I saw u mention on steam forum that it is problem for "older" windows 7 systems. But i am running up to date sp1,i am baffled ..

**Comment by Nariaftw** [comment]
Try installing this https://support.microsoft.com/en-us/kb/2670838

**Comment by IceLancerSR** [comment]
as u can see 05/13/2016 15:34:39.562: Importing CreateDXGIFactory{1|2} its already working.
problem is found as i said. its DPI awareness that is forced in this dll, and is not supported by win7 , min requirements is windows 8

**Comment by Kaldaien** [comment]
This should be rectified in 0.0.2

**Comment by IceLancerSR** [comment]
@Kaldaien 
Thanks its working now!
Just need to see if its possible to hack playstation gamepad icons in game instead of freaking xbox :+1:
