### ISSUE TITLE
Feature request: screenshot button

### ISSUE THREAD

**Issue by Himeko7** [Kaldaien/UnX#20]
It would be nice to have a gamepad mapping to take a screenshot of the game.

**Comment by Kaldaien** [comment]
Through Steam? I can work something out using SteamAPI.

You do realize that Steam already has one though, right? Provided you play in Big Picture Mode.

**Comment by Himeko7** [comment]
Not using BP mode, it's kinda laggy and messes other apps up sometimes. Hmm never looked at SteamAPI (didn't even know it existed), normally I'd do something like this~

* Find the game window handle ("Final Fantasy X")
* Get the window rect with GetClientRect within the desktop (avoid titlebar)
* Translate the coords with ClientToScreen
* Get the desktop window DC
* BitBlt the game window rect from the desktop DC into a bitmap
* Save to jpg/png ~

**Comment by Kaldaien** [comment]
Yeah, there's no way I'm doing that, heheh.

That relies on undefined behavior starting in Windows Vista. That uses GDI to grab the front buffer, but the front buffer is owned by the DWM. My day job deals with OpenGL so I know some pretty obscure stuff, I suppose :P 
 
I'll use the Steam API method, it's more efficient, plus the screenshot goes straight to your library for you to manage later. I'm familiar with this from work on my achievement system (which has an option to save screenshots when you unlock one).

**Comment by Himeko7** [comment]
I see, nice, can't wait for this :3 will donate again when on your next update, thanks for this awesome mod :D

**Comment by Kaldaien** [comment]
This is a core feature in 0.2.3+
