### ISSUE TITLE
Bugs attack... not kidding :)

### ISSUE THREAD

**Issue by IceLancerSR** [Kaldaien/UnX#21]
There are some very weird bugs in 0.22
1.mouse is no longer self hiding it keeps lingering visible
2.letters in game have gone waka waka.. :)
http://imgur.com/xyTzCCH
game will crash if i attempt to click on any of it..

**Comment by IceLancerSR** [comment]
Problem is in unx, once i restored old unx but kept new dxgi letters are back to normal in game and mouse is self hiding properly.

**Comment by TheOne320** [comment]
Steam overlay is also broken.

**Comment by Kaldaien** [comment]
Grab the repackaged v 0.2.2

Fixes for compatibility with non-compliant 3rd party D3D11 software are largely to blame for all of these problems.

**Comment by IceLancerSR** [comment]
Nothing has changed with new repackaged

**Comment by Kaldaien** [comment]
Yeah, the mouse won't' hide until about 20 seconds worth of time have passed in order to fix compatibility problems. The rest of the stuff, who knows.

**Comment by Kaldaien** [comment]
Both problems should be fixed in the re-release of 0.2.2

**Comment by IceLancerSR** [comment]
Alright tested 0.22a.
Letters are back to normal.
and mouse is hiding good again :)
Case closed for me
