### ISSUE TITLE
Help Menu Bugs

### ISSUE THREAD

**Issue by PMiley** [Kaldaien/UnX#22]
In version 0.2.2 the help menu and terminals are glitchy. The text appears corrupted and the game is prone to crash if you go into some of the tutorials.
![20160521180153_1](https://cloud.githubusercontent.com/assets/16994318/15451559/49d9223a-1f7e-11e6-8373-217f832be81f.jpg)

**Comment by Kaldaien** [comment]
Try the standalone DLL on the 0.2.2 release page

**Comment by PMiley** [comment]
That worked.

**Comment by Kaldaien** [comment]
Excellent, I will re-release the software then.
