### ISSUE TITLE
0.22b can't adjust/relocate the game window through an external app

### ISSUE THREAD

**Issue by Himeko7** [Kaldaien/UnX#25]
Up to the previous version I was using an app called "Games Relocator Window" (http://gwr.orekaria.com/) which lets you remove the window borders/titlebar and move the window to the top left corner of the current monitor it's on. So I would start the game, move it to my 3rd monitor (50" plasma TV) then use this app to achieve the same as "Borderless Mode" from the settings. However since 0.22 this doesn't work anymore.

**Comment by Kaldaien** [comment]
Has anything changed in 0.3.0? I've been fooling with window management performance a lot and may have broken and then fixed something :)

**Comment by Himeko7** [comment]
Seems fixed in 0,3, thank you! :)
