### ISSUE TITLE
RTSS OSD

### ISSUE THREAD

**Issue by FlipVS** [Kaldaien/UnX#28]
after using your rtss overlay I now have that appearing in all my games, I think its bugged. how can I solve this ?

**Comment by Kaldaien** [comment]
RTSS will enable itself in all games, you have to create a list of exceptions if you don't want it showing up elsewhere.

When the mod's not running and the game shuts down correctly this won't be a problem.

**Comment by FlipVS** [comment]
I'm sorry, I was talking about your actual part of the osd, the one from the mod. I think it bugged out or something cos it also appeared when I played other games on steam such as CSGO or Payday 2. I fixed it by disabling it on the .ini and restarting FFX-2 (which is the one I'm playing atm, I think it also would have worked if I chose FFX instead).
