### ISSUE TITLE
Instant crash at startup

### ISSUE THREAD

**Issue by KochiyaShiina** [Kaldaien/UnX#29]
As soon as I run the game it crashes.  This has been happening for me since v0.2.0 (the first version I've tried) and occurs regardless of the game chosen (FFX, X-2, Eternal Calm, or Will), although only with your mod; it runs fine without any mods.  If started through Steam, it gives no error messages, but if I launch the .exe files directly (either the launcher .exe or the game .exes themselves) I get an error.

Originally the error was that d3d11.dll was missing from my system.  I was running Windows Vista Home Premium x64 SP1 at the time, which includes only DX10, so I updated to SP2 and installed DX11.  Now the error is "The procedure entry point K32GetModuleBaseNameW could not be located in the dynamic link library KERNEL32.dll."

The crash occurs immediately, the game window doesn't even appear first, and neither the UnX_Language.ini nor a log file for your mod are generated.  I've tried running as administrator (for both the games and launcher) and in WinXP SP2 compatibility mode, but to no avail.  I don't have any other mods installed, nor any alternate software that interacts with DirectX (to my knowledge at least), and even if I use the default settings only in your .ini files the crash still happens.

My system is as follows:
OS - Windows Vista Home Premium SP2 x64
CPU - Intel Core2Quad Q6600 (note: overclocked to 3.04 ghz/core)
Mobo - Asus P5Q Deluxe (note: no onboard graphics chipset)
GPU - XFX/AMD Radeon HD 6870
RAM - I'm unsure of the exact model but it's 2x2GB of dual-channel Corsair DDR2-800/5-5-5-15 overclocked to DDR2-807/4-4-4-12
HDD - Western Digital WD6400AAKS-00A7B0 (640GB/7200RPM/SATA2)
PSU - Antec TruePower Quattro 850W

Edit: Oh, and I'm not using any gamepads BTW.  Just my mouse and keyboard.

**Comment by Kaldaien** [comment]
Yeah, there are too many things about your system that I cannot support, sorry.

I can fix the `K32GetModuleBaseNameW` problem, but I cannot fix the D3D10 problem.

**Comment by Kaldaien** [comment]
This may be enough fo fix `K32GetModuleBaseNameW`, but I don't know about the rest of your system. I think you're going to fall well below the minimum specs:

[dxgi.zip](https://github.com/Kaldaien/UnX/files/283278/dxgi.zip)

**Comment by shinra358** [comment]
I just had this problem and was about to write a post about it. It's the default dxgi.ini settings. Everythng that says show=, I made show = false. Bascially I went through everything and turned them off and that made the game start again.

**Comment by KochiyaShiina** [comment]
=D

@kal: It worked \o/!  FFX gave me a "your key bindings are corrupt, resetting to default" warning at the beginning, but other than that, no problems so far.  The Japanese audio + English subtitles works, which was my primary reason for using your mod.  Thanks =)

Just out of curiosity though, if you want to explain and have the time, what do you mean by falling below the minimum specs?  Other than my missing a discrete sound card, my system is well above the recommended specs for the FFX/X-2 HD Remaster...

@shinra: I'll keep that in mind in case something goes wacky again in the future.  =)

**Comment by Kaldaien** [comment]
D3D10 is below the minimum specifications for my mod. I am never going to re-write it to support D3D10, so if you don't have D3D11, you're plum out of luck.

**Comment by KochiyaShiina** [comment]
You might've missed the part of my initial comment where I mentioned that I upgraded to DX11.  =P

**Comment by Kaldaien** [comment]
No, I saw that. My point was that your system as it originally existed was running D3D10. There's potentially other APIs that I expect any D3D11 system to have that I cannot be guaranteed a Windows Vista system has.

**Comment by KochiyaShiina** [comment]
Ah, okay.  Well, if it comes to that, in theory I could install SP3 later on in case it might help, or even upgrade to Win7 at some point.  No problems yet though!  =)

Also, thanks again.  \o/

**Comment by shinra358** [comment]
Any reason that reshade is not working? If I start it with reshade the first time, it crashes with no error. If I start it a 2nd time, it says No Effects Loaded through reshade.
