### ISSUE TITLE
Crash of starting videos

### ISSUE THREAD

**Issue by jbarcalalorenzo** [Kaldaien/UnX#30]
Hi ho!

When the game go to run a video it´s crash with this message the file magicFiles/FFX/magic_0208.dll not found or it´s damage :S 

Last version of the UnX installed

**Comment by Kaldaien** [comment]
Fix your anti-virus software and then re-validate the Steam cache. AV software tends to prevent all of those magic DLLs that the game needs from loading, and then you're royally screwed.

**Comment by jbarcalalorenzo** [comment]
I´ll do it thanks!
