### ISSUE TITLE
Button Mod Not Working in the Controller Config in Esc Menu

### ISSUE THREAD

**Issue by shinra358** [Kaldaien/UnX#35]
Button mod doesn't include the buttons in the controller config section in the Esc menu.

**Comment by Kaldaien** [comment]
Of course not, those are words, not button icons

**Comment by shinra358** [comment]
Which means said 'letters' should be included in the button packs for the replacement just like the buttons. Or are you trying to say that you can't do them like that?

**Comment by Kaldaien** [comment]
I cannot modify text with textures

**Comment by shinra358** [comment]
So those letters are linking to all the other letters and not separated from those controller letters. Doh!
