### ISSUE TITLE
(Solved) Game crashes on version 0.5.4 duo to texture caching and is solved by rolling back to 0.5.3

### ISSUE THREAD

**Issue by DedSec55** [Kaldaien/UnX#41]
So I started playing this game with UnX and noticed that it crashed after the first fight with Auron. I removed UnX to pass that scene and get to the point where you can save for the first time. I saved, reinstalled UnX with the same settings as before and tried to proceed with the game - it crashed again.

Is there any way to fix this? Does this issue occure because I use Discord? I even disabled the overlay function and closed the program and tried playing again. It didn't work and crashed.

I would appreciate any help. Thank you very much.

**Comment by Kaldaien** [comment]
Use dsgi.dll from v 0.5.3 to get passed that scene. There is a problem with the game's memory management at that point that wasn't exposed until I added texture caching.

**Comment by DedSec55** [comment]
Wow, thank you very much for your fast answer. Do you mean by using JUST replaced the 0.5.1 ddl with the 0.5.3 one? Because I just did that and it still crashes. If you are 100% sure, I must have done something wrong.
