### ISSUE TITLE
Game is crashing when I enter Mushroom Rock Road and walk past the NPC's to start the  The Dark Magus Sisters encounter 100% of the time.

### ISSUE THREAD

**Issue by Zanroth** [Kaldaien/UnX#42]
Game is crashing when I enter Mushroom Rock Road and walk past the NPC's to start the The Dark Magus Sisters encounter 100% of the time.

[logs.zip](https://github.com/Kaldaien/UnX/files/305868/logs.zip)

**Comment by DedSec55** [comment]
Which version are you using? If you are using 0.5.4, try rolling back to 0.5.3. This fixed a crashing issue for me.

**Comment by Kaldaien** [comment]
This should be fixed in 0.5.4a, let me know.

**Comment by Zanroth** [comment]
Yes its fixed thank you!
