### ISSUE TITLE
Feature request: Fix Thunder Plains mini game

### ISSUE THREAD

**Issue by DoHe** [Kaldaien/UnX#45]
The vanilla version of FFX-2 has a bug with the Thunder Plains tower calibration mini game. In the southern half, all mini games use small buttons instead of the enlarged version as the northern half does.
As you can see [here](http://steamcommunity.com/app/359870/discussions/0/364042262873209373) it's not just me.
Is there any way to fix this through your mod?

**Comment by Kaldaien** [comment]
I cannot fix this, sorry.
