### ISSUE TITLE
Feature request: Auto updater

### ISSUE THREAD

**Issue by Th3MadHatter** [Kaldaien/UnX#46]
Fairly simple, just a short script that checks for commits on load and updates if needed. Saves time dealing with people running old versions and it saves time for users who don't know what they're doing (need to manually update) and those that do (update through git manually).

A startup delay could be added if an update is found so it makes sure its running the latest version before starting the game but that would require a launcher replacement.

Great project, many thanks for this :+1:

**Comment by Kaldaien** [comment]
The project's wound down into long-term maintenance mode at this point. Updates are not frequent enough to justify this.

HOWEVER, this is something I am looking into for future projects. `dxgi.dll` from this project enhances any D3D9/11/12 or GL game and sometime in the future it will be a standalone product with an interface similar to GeDoSaTo. That tool would be where the auto-update procedure would live, but I haven't even started to think about its design yet.

**Comment by Kaldaien** [comment]
Auto-update was added in 0.7.x, just never got around to closing this ;)
