### ISSUE TITLE
CreateFile2 could not be located in kernel32.dll (pre-release)

### ISSUE THREAD

**Issue by Th3MadHatter** [Kaldaien/UnX#47]
I tried the pre-release version that was up just for fun, as soon as I try and load any of the games I get the error mentioned in the topic. It doesn't generate a log file. The launcher DOES load, the games unfortunately don't.

The games work great with the older version but thought I might report this anyway since there might be a #define missing(?) or something like that in the new pre-RC or dependencies are missing out of the box.
Crashes with both the normal and 64 dll on Win 7 64bit.

**Comment by Kaldaien** [comment]
This was fixed a long time ago, thank you for reporting it though :)

There are plenty of other, more serious, problems with the pre-release that you would have noticed if you were not running Windows 7. All that stuff is fixed in the official release.
