### ISSUE TITLE
[Suggestion] Dualshock controller button icons

### ISSUE THREAD

**Issue by Scellow** [Kaldaien/UnX#5]
I don't know if it's possible but do you think it's possible to use dualshock controller buttons ?

**Comment by Nariaftw** [comment]
Already requested :) #1

**Comment by Scellow** [comment]
Oh my bad, i should go sleep i think (it's already midnight here :p)

**Comment by Nariaftw** [comment]
Hey it only shows more interest in it as a feature :D

**Comment by Kaldaien** [comment]
I will be working on this, I have to add support for dumping and replacing textures in d3d11 games though. It's simple to do in GL and d3d9, but I have very little experience with d3d11 under my belt right now.
