### ISSUE TITLE
Enhancement: Texture Priority 

### ISSUE THREAD

**Issue by xinthefreefallx** [Kaldaien/UnX#50]
Just a small recommendation for a later version:

Anyway to add a priority for textures added? Like newly dumped textures taking priority over the textures dumped from the previous versions?

I've noticed when you have two files from two different versions injected, they actually just cancel each other out and the game loads the default textures.

Makes it a tad difficult when I add my textures in that were originally dumped from 0.6 and they're fighting against the Better Textures Mod which features textures dumped from previous versions. I've spent like 30 minutes trying to weed out the textures and I always end up missing one and things end up switching back and forth between textures.

Just more or less an ease of use request.

**Comment by Kaldaien** [comment]
This should be fixed in v 0.6.2, which I will upload momentarily.
