### ISSUE TITLE
Command prompt popping out from nowhere

### ISSUE THREAD

**Issue by carella96** [Kaldaien/UnX#54]
Hello,
since the release 0.6.2 of UnX which requires MSVC++ 2015 Runtime, I can't run UnX so I'm stucked with the 0.6.1 ver.
On the 0.6.6, I actually get the game stucked on a blank screen and a cmd popping out from nowhere everytime I try to run FFX...
I'm currently running FFX on Win10 (not the anniversary edition), on a fx8350 and a gtx960, and I've already tried to run FFX, both the launcher both the game, as admin in compatibility mode.
![screen](https://cloud.githubusercontent.com/assets/22392781/18783301/545e5968-818b-11e6-9ef8-463a2e6e5824.jpg)

Any help would be appreciated, thanks!

**Comment by carella96** [comment]
Ah, on the 0.6.5 it just crashes alone without even going to the blank screen. Am I missing some components?

**Comment by Kaldaien** [comment]
That prevents Steam from killing the game when Steam crashes, you should leave that on because the latest releases of Steam are very unstable. You can turn it off with `OutputDebug=false`.

**Comment by carella96** [comment]
Thanks, I'll try it out. 
Anyway still a blank screen on the v0.6.8
I guess I'll stick with the 0.6.3, just some random crashes in the omega ruins, but considering how much the game has improved with UnX I'm fine.

**Comment by Kaldaien** [comment]
This feature has been disabled (0.8.4), it should no longer be necessary.
