### ISSUE TITLE
Any plans to support 21:9 aspect ratio in the future?

### ISSUE THREAD

**Issue by DedSec55** [Kaldaien/UnX#57]
First of all, let me apologize for writing this in the issue section, but I just couldn't find another way to make a "feature request".

So, what are your plans on this, if you have any? I know that there is a solution for streched 21:9, but that isn't really the thing that I hoped for. There is a guy who made it work with Cheat Engine, but I got no further information on the current state of his workaround.

Here is a proof image: http://imgur.com/6ZJBCQe
Source: http://www.wsgf.org/forums/viewtopic.php?t=31094

Thank you very much for your work until now. I'm curious about your answer on this matter.

Grettings,
DedSec55

**Comment by Kaldaien** [comment]
It seems unlikely :-\

I can't completely rule this out, but those pre-rendered backgrounds and fixed camera angles are almost a perfect storm and the only way Square-Enix managed to make certain parts of the game work at 16:9 was by dollying the camera much farther in than it should be and cropping some of the backgrounds.

Without doing the same thing, you will see empty space on the left and right and eventually the game becomes unplayable when the camera is 2 inches away from Tidus :P
