### ISSUE TITLE
Special K can't find my Final Fantasy X-X2 HD Remaster

### ISSUE THREAD

**Issue by ishihinoki** [Kaldaien/UnX#58]
The game keep "not responding" when I install "Untitled" Project X" manual. Then I use SKIM64 but it can't find my game, I reinstall it many times but it's still not working.
P/s: I'm using the one cracked by CODEX.

**Comment by Kaldaien** [comment]
That's by design. The stuff that was done to circumvent Steam DRM only goes as far as the unmodified game. I have effectively added Steam DRM back. You will have to buy the game, I cannot condone piracy.
