### ISSUE TITLE
Still hanging in initializing NvAPI

### ISSUE THREAD

**Issue by vOidSenses** [Kaldaien/UnX#6]
Hey. I added the entry that supposedly fixes this issue. I also updated the dll but it still crashes after pressing play from the launcher and the log is still saying Initializing NvAPI

Any ideas or ways that I can test something else?

**Comment by Kaldaien** [comment]
If you added the entry correctly, it wouldn't even try to initialize NvAPI. This is pretty baffling. It should just go straight to Initiailizing NvAPI: failed.

Try 0.0.3, its included ini file has everything setup and you just need to change Disable from false to true.

**Comment by IceLancerSR** [comment]
it would help to know your driver version , os as well.
i have dual boot win7 and win10 , one with drivers 364 other with 365 on gtx 950, and no crashes since v2.

**Comment by vOidSenses** [comment]
Yep it worked, could it be bad characters when copying or something? I was using notepad.

Just so you know I'm using win7 64, a 980m running the latest drivers.

Anyway it's fixed, thx ;)
