### ISSUE TITLE
Issues Istalling

### ISSUE THREAD

**Issue by keeganp218** [Kaldaien/UnX#60]
I can't figure it out for the life of me. I placed all the files in the root folder of the game, but UnX isn't working. I wish there was a read me or something, as googling for help brought up nothing. Thanks.

**Comment by Kaldaien** [comment]
I imagine you figured it out by now, but for future reference, I have very thorough guides on Steam for all of my mods. As soon as I write a mod that's not for a Steam game, I will have to come up with a different policy :)

The whole thing works well as long as you don't land on the GitHub page randomly. I don't want to write a Wiki here and a Guide on Steam.

**Comment by keeganp218** [comment]
Yes, your Steam guide is VERY thorough, well written and easy to read. However, when I finally got around to installing UnX yesterday, Steam was down for an hour or two. I couldn't figure out how to install UnX, as for some reason just extracting the files to the game's root wasn't working. Special K helped a lot. 

Thanks for the awesome mod!
