### ISSUE TITLE
Constant crashes :(

### ISSUE THREAD

**Issue by ShadwDrgn** [Kaldaien/UnX#65]
I very frequently get crashes when using Untitled X. I don't seem to get them when without it, but it's hard to say since I make liberal use of the fast forward functionality. I've zipped up my log folder from directly after the last crash. I can provide any information you like, as I've got experience in development and am reasonably fluent in hardware and software. Please let me know how/if i can provide more information to hopefully get this resolved if it's possible at all. Thanks for this AWESOME program. It would have taken me WAY longer to get where I am in game without your awesome fast forward functionality.
[logs.zip](https://github.com/Kaldaien/UnX/files/676226/logs.zip)

**Comment by ShadwDrgn** [comment]
Also it's worth noting when I last played it updated, and this crash log is from AFTER that update. That was today.

**Comment by Kaldaien** [comment]
That's the biggest problem with running this game on an Intel GPU. Iggy, the Flash virtual machine that handles video playback and the UI constantly crashes.

If you actually have a dedicated GPU, it's advisable that you setup your driver accordingly to run the game on it instead of the Intel GPU. In some cases where the driver isn't able to be setup that way, you can turn on the Intel GPU bypass in UnX.ini.

If you ONLY have an Intel GPU, I'm not sure what to tell you. It should never have been stable in the first place, modified or unmodified, from the user reports I've seen.

**Comment by Kaldaien** [comment]
The only thing that comes to mind given that stack trace (in particular, the IME composition part) is a possible problem with touch input services. If this is a touchscreen laptop, it may do you well to disable those in `services.msc` and try running the game again. This causes problems in a couple of other games as well.

**Comment by Kaldaien** [comment]
Also, is that log really and truly from after the update? The last update I pushed to the server was 0.8.3.4, that reads 0.8.2.1.

**Comment by ShadwDrgn** [comment]
I did a manual install i think, so i'll go switch to that. It's not a laptop. It's actually a NUC. The PS4 controller has a touchpad on it, and i' noticed that the mouse isn't disappearing after that update either. I'll reinstall and do a full reconfigure, I suppose. Could me running on intel HD pro 580 graphics be causing an issue due to the feature meant to disable intel graphics? I did notice a lot of errors in the dxgi log about the video card disappearing or something. Will update again after install via skim64

**Comment by ShadwDrgn** [comment]
update. I can't uninstall unx because the gamepad folder is just magically held by windows 10 indefinitely with UAC disabled and me as a local admin running a cmd prompt AS admin can't even take ownership of the gamepad folder to delete it or view it's permissions. I don't understand how this is possible, but UnX is now permenantly on my computer for all of eternity :~(

**Comment by ShadwDrgn** [comment]
Update: installed newest version via skim64. Appears to be correct version. Here's the newest crash logs. Your mention of a touchpad makes me concerned this might have something to do with DS4Windows which I use to ensure steam works properly and games that require xinput work fine. If I get rid of it it'll fix ffx but break many other games. Can i just disable whatever is in unx that's playing with the controller? or is this caused by something else?

**Comment by ShadwDrgn** [comment]
The video stops and the game seems to keep playing in the background. If I press buttons I can hear the menu selection changing, but if I press the hotkeys for bringing up the system menu (L2, Select, R2) the game fully crashes with the sound I assume your program introduces. I really appreciate your looking at this. It's awesome that you are making this and helping out the community.

**Comment by Kaldaien** [comment]
From the sounds of things, the Steam client actually crashed. The mod's designed to keep the game running instead of immediately crashing to desktop when that happens. It usually gives you enough time to save your game or do whatever before the game eventually crashes because the Steam client's no longer running.

This may, in fact, be related to third-party controller software. The latest Steam client has built-in support for DualShock 4 controllers and makes them behaves like XInput - that makes DS4Windows obsolete.

**Comment by ShadwDrgn** [comment]
I tried using the PS4 controller support in steam and half my games stopped working. Spelunky is one example. It doesn't seem to map anything as xinput. Also I've removed DS4Windows and played with UnX without it with just the PS4 controller and no wrapper and these crashes still happen. Steam seems to be running fine in the background when this happens.

Also until todays update I was able to run FFX.exe directly to load the game and your mod and now it just black screens when i do that. Also when playing with the steam big picture mode and the launcher as usual the game still crashes after that update that just released a few minutes ago. :( This is definitely not a controller driver issue unless it's a problem with directinput in general. :~(

**Comment by ShadwDrgn** [comment]
I just tested again with PS4 controller support and the dpad completely stops working in steam, in FFX the start button brings up the system menu and you can't start the game because no button translates to the actual start button. Basically from what I can tell steam's PS4 controller support completely breaks the controller. :~( also tested with the PS4 controller again as a dinput device only and the game still crasshes

**Comment by ShadwDrgn** [comment]
you can just close this thread actually. It looks like the game DOES crash without your mod too it just takes a lot longer to happen. I renamed the two DLLs and was able to get past the scene that was crashing me but about 30 minutes later it finally did crash even without your mod. apparently SE just doesn't know how to make stable games. Sorry to waste all your time :(
