### ISSUE TITLE
Mods arent working with the new update.

### ISSUE THREAD

**Issue by parker966** [Kaldaien/UnX#66]
hello first time on here, love your mod. im having issues with the new update you released today, im using a bunch of texture mods from nexusmods and right now they arent working.
they were working before the update so i figure that might have something to do with it. if you could either let me know what i can do or possibly tell me how to downgrade to the previous update. 
let me know if i need to submit anything that can help and again love your work man thanks.

**Comment by Kaldaien** [comment]
Please run SKIM64.exe and do an uninstall / install.

I just pushed 0.8.5 to the update servers, but you'll be waiting 6-11 hours for that to have any affect on you unless you just uninstall and re-install.

I believe 0.8.5 fixes this problem for people affected by it.

**Comment by parker966** [comment]
confirmed, works just like you said, thanks Kaldaien :D :1st_place_medal: :+1: :100:
