### ISSUE TITLE
FFX Force Closes

### ISSUE THREAD

**Issue by Roxaslenobody** [Kaldaien/UnX#67]
After updating to 0.8.5 opening FFX loads a black screen, then the sound from metal gear solid when you're detected plays, then the game will automatically close to desktop

**Comment by Roxaslenobody** [comment]
It was working for 0.8.4 but when after updating when it told me to it started doing this if that's any help as well

**Comment by Kaldaien** [comment]
Please use 0.8.6, run SKIM64 and uninstall and re-install.

There's a chance you have a bad set of config files, so also go into the install directory and delete all of the INI files by hand.

**Comment by Roxaslenobody** [comment]
Updated to 0.8.6, i tried uninstalling, reinstalling same issue, i deleted the ini files still get the same issues, but the interesting thing is if i use the testing and merge it it suddenly works but i rather use the main one and not testing files

**Comment by Kaldaien** [comment]
I really can't help you without seeing your logs...

**Comment by Roxaslenobody** [comment]
[dxgi.txt](https://github.com/Kaldaien/UnX/files/685798/dxgi.txt)
[crash.txt](https://github.com/Kaldaien/UnX/files/685799/crash.txt)
[CEGUI.txt](https://github.com/Kaldaien/UnX/files/685803/CEGUI.txt)
[Unx.txt](https://github.com/Kaldaien/UnX/files/685800/Unx.txt)
[steam_api.txt](https://github.com/Kaldaien/UnX/files/685802/steam_api.txt)
[preloads.txt](https://github.com/Kaldaien/UnX/files/685801/preloads.txt)
 I believe these are the logs you need

**Comment by Kaldaien** [comment]
Can you run [SKIM64.exe](https://github.com/Kaldaien/SpecialK/releases/download/sk_appinit/SKIM64.exe) and uninstall and re-install the mod?

I uploaded 0.8.6.1, which should spit out some more useful information (if it doesn't fix the problem). You won't be getting an upgrade notification for that version, so re-installing is the only way to get it.

**Comment by Roxaslenobody** [comment]
Updated to latest version and still receive crashes

**Comment by Roxaslenobody** [comment]
[CEGUI.txt](https://github.com/Kaldaien/UnX/files/686498/CEGUI.txt)
[crash.txt](https://github.com/Kaldaien/UnX/files/686494/crash.txt)
[dxgi.txt](https://github.com/Kaldaien/UnX/files/686495/dxgi.txt)
[preloads.txt](https://github.com/Kaldaien/UnX/files/686497/preloads.txt)
[UnX.txt](https://github.com/Kaldaien/UnX/files/686496/UnX.txt)
Here are the logs for the new update when it crashed

**Comment by Kaldaien** [comment]
To the best of my knowledge, this is now fixed in v 0.8.7, the install/update procedure for you will be the same. Just run SKIM64.

**Comment by Roxaslenobody** [comment]
There we go 0.8.7.1 works, thank you Kaldaien
