### ISSUE TITLE
UNX Boosters don't work

### ISSUE THREAD

**Issue by panthernet** [Kaldaien/UnX#70]
Hello, i'd played with UnX for FFX: HD Remastered for a while. Texture mods works fine, i see OSD info panel but it seems that features like **AP for all party** and **Sensor ability for everyone** isn't working.

I have them enabled in **UnX_Booster.ini** file and tried to use **Ctrl+ Shift + A** but no results so far. The AP gains are still per character and no info on screen or OSD (not sure if it should be).

Do you have any clues what's the problem might be?

UPD: i'd recompiled the **unx.dll** with these options **true** by default but results are the same :(
UPD2: tried to remove all custom stuff and install clean UNX - still bugged :(

**Comment by panthernet** [comment]
Configs somehow messed up i suppose. Fixed by applying default content to dxgi.ini.

**Comment by Spiffo89** [comment]
I have this same problem. How do you apply default content to dxgi.ini? I just cant get AP or Sensor boosters to work. Everything else works fine.
