### ISSUE TITLE
Corrupted file

### ISSUE THREAD

**Issue by burandon** [Kaldaien/UnX#8]
I downloaded v0.0.4 unx.zip but when I try to extract it with WinRar, it says the archive is corrupted.

**Comment by Nariaftw** [comment]
Try opening it in 7zip. Others have mentioned the same about the built in windows client and winrar, but it worked fine for me (though it did complain) with 7zip. Another on the forum thread mentioned he or she had luck with upgrading WinRar.

**Comment by Kaldaien** [comment]
This has been fixed
