### ISSUE TITLE
Automatic installation is installing old version v0.8.7 instead of v.0.9.0

### ISSUE THREAD

**Issue by amnah** [Kaldaien/UnX#80]
I recently did a fresh install of FF X/X-2 HD Remaster on steam. I am following the directions from here: 

https://steamcommunity.com/sharedfiles/filedetails/?id=683802394

Downloaded the SKIM64 from here (tried both, both gave same results):

https://github.com/Kaldaien/FAR/releases/download/far_057/SKIM64.exe
https://github.com/Kaldaien/FAR/releases/download/far_070/SKIM64.exe

After installing, it says UNX_0_8_7,31

![unx](https://user-images.githubusercontent.com/2630503/29603724-3add89e4-87b3-11e7-8f5d-9f3d94b2bcdf.png)

Am I doing something wrong?

**Comment by Kaldaien** [comment]
No, I temporarily rolled stuff back. 0.9.x should be release ready now.
