### ISSUE TITLE
Please release the source code

### ISSUE THREAD

**Issue by jtrees** [Kaldaien/UnX#9]
A source code release would make it easier for others to contribute and increase the audience since many people don't appear comfortable running modified "exe"s without knowing what was modified.

**Comment by Kaldaien** [comment]
The disclaimer from the development thread still applies, I have every intention to release the source code, but it's hobbled together from several other projects and needs to be cleaned up first:

><h5>Source Code</h5>
>>Source code ***will*** be available in the future, I literally threw this thing together using bits and pieces from my other mods in about an hour's work. When I get things cleaned up, check back on the GitHub repository.

**Comment by Kaldaien** [comment]
Code has been checked-in.
