### ISSUE TITLE
Project Still Active?

### ISSUE THREAD

**Issue by JPVenson** [Kaldaien/UnX#95]
Hey @Kaldaien,

Is this Projekt still actively maintained by you? There seem not to be any responses for 4-6 years now. If not so please give a small note on the readme so anybody can see that this repository is no longer maintained.

**Comment by Kaldaien** [comment]
No, it is not. I did not even have access to my GitHub account until recently :)

I do still support the Special K plug-in, however. A standalone version is deployed through Special K's Wiki.
